import = [
    "/Users/sstanfield/.alacritty.local.toml",
    "/Users/sstanfield/.config/alacritty/themes/themes/dracula.toml",
]
live_config_reload = true

window.option_as_alt = "Both"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 4
y = 0
