live_config_reload: true

font:
  size: 22
  normal:
    family: JetBrainsMono Nerd Font
      # family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
    # <C-v>uf00c: 
    # <C-v>uf110: 
    # <C-v>uf129: 
    # <C-v>uf05e: 

import:
  - dracula.yml

  # Normal colors
key_bindings:
  - {key: Return, mods: Command, action: ToggleSimpleFullscreen}
  - {key: Return, mods: Shift, chars: "\e[13;2u"}
  - {key: Return, mods: Control, chars: "\e[13;5u"}

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 120
    lines: 50
  padding:
    x: 4
    y: 0

theme: Dracula
