live_config_reload: true

font:
  size: 22
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
    # <C-v>uf00c: 
    # <C-v>uf110: 
    # <C-v>uf129: 
    # <C-v>uf05e: 

colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black: '#000000'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#caa9fa'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#bfbfbf'

  # Bright colors
  bright:
    black: '#575b70'
    red: '#ff6e67'
    green: '#5af78e'
    yellow: '#f4f99d'
    blue: '#caa9fa'
    magenta: '#ff92d0'
    cyan: '#9aedfe'
    white: '#e6e6e6'

key_bindings:
  - {
      key: Return,
      mods: Command,
      action: ToggleSimpleFullscreen
    }

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 120
    lines: 50
  padding:
    x: 4
    y: 0

theme: Dracula
