live_config_reload: true

font:
  size: 22
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
    # <C-v>uf00c: 
    # <C-v>uf110: 
    # <C-v>uf129: 
    # <C-v>uf05e: 

colors:
  # COLORSCHEME: base16-atelier-sulphurpool.yml
  # Default colors
  primary:
    background: '0x202746'
    foreground: '0x979db4'

  # Colors the cursor will use if `custom_cursor_colors` is true
  normal:
    black: '0x202746'
    red: '0xc94922'
    green: '0xac9739'
    yellow: '0xc08b30'
    blue: '0x3d8fd1'
    magenta: '0x6679cc'
    cyan: '0x22a2c9'
    white: '0x979db4'

  # Bright colors
  bright:
    black: '0x6b7394'
    red: '0xc76b29'
    green: '0x293256'
    yellow: '0x5e6687'
    blue: '0x898ea4'
    magenta: '0xdfe2f1'
    cyan: '0x9c637a'
    white: '0xf5f7ff'

  cursor:
    text: '0x202746'
    cursor: '0x979db4'

  # Normal colors
key_bindings:
  - {key: Return, mods: Command, action: ToggleSimpleFullscreen}
  - {key: Return, mods: Shift, chars: "\e[13;2u"}
  - {key: Return, mods: Control, chars: "\e[13;5u"}

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 120
    lines: 50
  padding:
    x: 4
    y: 0

theme: Dracula
