import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

# Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas

# brew install --cask font-monaspice-mono-nerd-font font-jetbrains-mono-nerd-font

[font]
size = 20
# normal = { family = "MonaspiceNe Nerd Font Mono", style = "Regular" }
# bold = { family = "MonaspiceNe Nerd Font Mono", style = "Bold" }
# italic = { family = "MonaspiceRn Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "MonaspiceRn Nerd Font Mono", style = "Regular" }

normal = { family = "Menlo", style = "Regular" }
bold = { family = "Menlo", style = "Bold" }
italic = { family = "Menlo", style = "Italic" }
bold_italic = { family = "Menlo", style = "Regular" }


[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 4
y = 0
