import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

# Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas

[font]
size = 22

#  brew install --cask font-monaspice-mono-nerd-font

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MonaspiceNe Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 4
y = 0
